#!/bin/bash

echo "========================================="
echo "✅ VERIFYING MODULE UNLOCKING FIX"
echo "========================================="

echo "Your app is live at:"
echo "https://dsca-mta-quiz01.vercel.app"
echo ""
echo "========================================="
echo "🧪 TEST INSTRUCTIONS"
echo "========================================="
echo ""
echo "1. Open the app: https://dsca-mta-quiz01.vercel.app"
echo ""
echo "2. Login as a trainee (use existing credentials)"
echo ""
echo "3. Complete Module 4 (End of Life Care)"
echo "   - Answer all 20 questions"
echo "   - Submit the assessment"
echo ""
echo "4. After the results screen, click 'Return to Dashboard'"
echo ""
echo "5. Module 5 should now show as 'Available' instead of 'Locked'"
echo "   - The 'Start Module' button should appear"
echo ""
echo "6. Click 'Start Module' on Module 5 to verify it works"
echo ""
echo "========================================="
echo "🔍 Admin Login (if needed):"
echo "========================================="
echo "Email: admin@careworks.com"
echo "Password: Admin@2025"
echo ""
echo "========================================="
echo "📊 Check deployment:"
echo "========================================="
vercel list --limit 3

echo ""
echo "Opening the app in your browser..."

open "https://dsca-mta-quiz01.vercel.app" 2>/dev/null || echo "Please open the URL manually: https://dsca-mta-quiz01.vercel.app"

