import jsPDF from 'jspdf';
import 'jspdf-autotable';

export const generateAssessmentReport = (reportData) => {
  const { user, module, attempt, questionsWithAnswers, startTime, endTime } = reportData;
  
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  
  // Header
  doc.setFillColor(30, 41, 59);
  doc.rect(0, 0, pageWidth, 45, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(20);
  doc.text('CareWorks Training Assessment Report', pageWidth / 2, 20, { align: 'center' });
  doc.setFontSize(10);
  doc.text('Official Training Record', pageWidth / 2, 33, { align: 'center' });
  
  doc.setTextColor(0, 0, 0);
  let yPos = 60;
  
  // User Information
  doc.setFillColor(248, 250, 252);
  doc.rect(14, yPos - 5, pageWidth - 28, 40, 'F');
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text('TRAINEE INFORMATION', 20, yPos);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text(`Name: ${user.name || user.email}`, 20, yPos + 8);
  doc.text(`Email: ${user.email}`, 20, yPos + 16);
  doc.text(`Organisation: ${user.organisation || 'Not specified'}`, 20, yPos + 24);
  yPos += 50;
  
  // Assessment Information
  doc.setFillColor(248, 250, 252);
  doc.rect(14, yPos - 5, pageWidth - 28, 35, 'F');
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text('ASSESSMENT INFORMATION', 20, yPos);
  doc.setFontSize(10);
  doc.text(`Module: ${module.name}`, 20, yPos + 8);
  doc.text(`Date: ${new Date(startTime).toLocaleString()}`, 20, yPos + 16);
  doc.text(`Duration: ${Math.floor((endTime - startTime) / 60000)} minutes`, 20, yPos + 24);
  yPos += 50;
  
  // Score Section
  const passed = attempt.passed;
  const percentage = (attempt.score / attempt.total) * 100;
  doc.setFillColor(passed ? 34 : 239, passed ? 197 : 68, passed ? 94 : 68);
  doc.rect(14, yPos - 5, pageWidth - 28, 35, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(14);
  doc.text(passed ? 'PASSED' : 'NOT PASSED', pageWidth / 2, yPos + 8, { align: 'center' });
  doc.setFontSize(11);
  doc.text(`Score: ${attempt.score} / ${attempt.total} (${percentage.toFixed(1)}%)`, pageWidth / 2, yPos + 22, { align: 'center' });
  doc.setTextColor(0, 0, 0);
  yPos += 45;
  
  // Questions Table
  doc.setFontSize(12);
  doc.setTextColor(30, 41, 59);
  doc.text('DETAILED QUESTION BREAKDOWN', 14, yPos);
  yPos += 8;
  
  const tableData = questionsWithAnswers.map((q, idx) => [
    idx + 1,
    q.text.length > 50 ? q.text.substring(0, 47) + '...' : q.text,
    q.userAnswer === 0 ? 'True' : 'False',
    q.correctAnswer === 0 ? 'True' : 'False',
    q.isCorrect ? '✓' : '✗'
  ]);
  
  doc.autoTable({
    startY: yPos,
    head: [['#', 'Question', 'Your Answer', 'Correct', 'Result']],
    body: tableData,
    theme: 'striped',
    headStyles: { fillColor: [79, 70, 229], textColor: [255, 255, 255] },
    columnStyles: {
      0: { cellWidth: 10, halign: 'center' },
      1: { cellWidth: 100 },
      2: { cellWidth: 25, halign: 'center' },
      3: { cellWidth: 25, halign: 'center' },
      4: { cellWidth: 15, halign: 'center' }
    },
    didDrawCell: (data) => {
      if (data.column.index === 4 && data.row.index >= 0) {
        const isCorrect = questionsWithAnswers[data.row.index]?.isCorrect;
        data.cell.setTextColor(isCorrect ? 34 : 239, isCorrect ? 197 : 68, isCorrect ? 94 : 68);
      }
    }
  });
  
  const finalY = doc.lastAutoTable.finalY + 10;
  doc.setFontSize(8);
  doc.setTextColor(100, 116, 139);
  doc.text('This is an official training record generated by CareWorks Training Platform.', pageWidth / 2, finalY, { align: 'center' });
  doc.text(`Generated: ${new Date().toLocaleString()}`, pageWidth / 2, finalY + 5, { align: 'center' });
  
  doc.save(`${user.name || user.email}_${module.name.replace(/[^a-z]/gi, '_')}_report.pdf`);
};

export const printReport = (reportData) => {
  const { user, module, attempt, questionsWithAnswers, startTime, endTime } = reportData;
  const printWindow = window.open('', '_blank');
  printWindow.document.write(`
    <!DOCTYPE html>
    <html>
    <head><title>Assessment Report - ${module.name}</title>
    <style>
      body { font-family: 'Segoe UI', Arial, sans-serif; padding: 40px; max-width: 1000px; margin: 0 auto; }
      .header { background: #1e293b; color: white; padding: 30px; text-align: center; border-radius: 12px; }
      .section { margin: 25px 0; padding: 20px; background: #f8fafc; border-radius: 12px; }
      .score { text-align: center; padding: 20px; border-radius: 12px; }
      .passed { background: #dcfce7; color: #166534; }
      .failed { background: #fee2e2; color: #991b1b; }
      table { width: 100%; border-collapse: collapse; margin-top: 15px; }
      th { background: #4f46e5; color: white; padding: 12px; text-align: left; }
      td { padding: 10px; border-bottom: 1px solid #e2e8f0; }
      .correct { color: #16a34a; font-weight: bold; }
      .incorrect { color: #dc2626; font-weight: bold; }
      @media print { body { padding: 0; } .no-print { display: none; } }
    </style>
    </head>
    <body>
      <div class="header">
        <h1>CareWorks Training Assessment Report</h1>
        <p>Official Training Record</p>
      </div>
      <div class="section">
        <h3>Trainee Information</h3>
        <p><strong>Name:</strong> ${user.name || user.email}</p>
        <p><strong>Email:</strong> ${user.email}</p>
        <p><strong>Organisation:</strong> ${user.organisation || 'Not specified'}</p>
      </div>
      <div class="section">
        <h3>Assessment Information</h3>
        <p><strong>Module:</strong> ${module.name}</p>
        <p><strong>Date:</strong> ${new Date(startTime).toLocaleString()}</p>
        <p><strong>Duration:</strong> ${Math.floor((endTime - startTime) / 60000)} minutes</p>
      </div>
      <div class="score ${attempt.passed ? 'passed' : 'failed'}">
        <h2>${attempt.passed ? '✓ PASSED' : '✗ NOT PASSED'}</h2>
        <div style="font-size: 32px; margin: 10px 0;">${attempt.score} / ${attempt.total}</div>
        <div>Score: ${((attempt.score / attempt.total) * 100).toFixed(1)}% | Required: ${attempt.passMark}/${attempt.total} (75%)</div>
      </div>
      <div class="section">
        <h3>Detailed Answers</h3>
        <table>
          <thead><tr><th>#</th><th>Question</th><th>Your Answer</th><th>Correct</th><th>Result</th></tr></thead>
          <tbody>
            ${questionsWithAnswers.map((q, idx) => `
              <tr>
                <td>${idx + 1}</td>
                <td>${q.text}</td>
                <td class="${!q.isCorrect ? 'incorrect' : ''}">${q.userAnswer === 0 ? 'True' : 'False'}</td>
                <td class="${!q.isCorrect ? 'correct' : ''}">${q.correctAnswer === 0 ? 'True' : 'False'}</td>
                <td class="${q.isCorrect ? 'correct' : 'incorrect'}">${q.isCorrect ? '✓' : '✗'}</td>
              </tr>
            `).join('')}
          </tbody>
        </table>
      </div>
      <div style="text-align: center; margin-top: 40px; color: #64748b; font-size: 12px;">
        <p>Generated on: ${new Date().toLocaleString()}</p>
      </div>
      <div class="no-print" style="text-align: center; margin-top: 20px;">
        <button onclick="window.print()" style="padding: 10px 24px; background: #4f46e5; color: white; border: none; border-radius: 8px; cursor: pointer;">🖨️ Print Report</button>
      </div>
    </body>
    </html>
  `);
  printWindow.document.close();
};
